In [1]:
# ============================================================
# FULL NOTEBOOK — Run as ONE cell after fresh runtime restart
# ============================================================

# --- INSTALL ---
!pip install -q transformers datasets accelerate peft trl bitsandbytes gradio

# --- IMPORTS ---
import torch
import gc
import pandas as pd
import numpy as np
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments
from peft import LoraConfig
from trl import SFTTrainer

print("GPU:", torch.cuda.get_device_name(0))
print("GPU memory:", round(torch.cuda.get_device_properties(0).total_memory / 1e9, 1), "GB")

# --- LOAD DATASET ---
dataset = load_dataset("gretelai/synthetic_text_to_sql")
print(f"Train: {len(dataset['train'])}, Test: {len(dataset['test'])}")

# --- LOAD MODEL (4-bit quantized) ---
MODEL_NAME = "mistralai/Mistral-7B-Instruct-v0.2"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
)
model.config.use_cache = False
print(f"Model loaded: {model.get_memory_footprint()/1e9:.1f} GB")

# --- HELPER FUNCTIONS ---
def create_prompt(sample):
    return f"""[INST] You are a helpful SQL assistant. Given the following database schema and a natural language question, generate the correct SQL query and explain what it does.

### Database Schema:
{sample["sql_context"]}

### Question:
{sample["sql_prompt"]}

### Response:
[/INST]"""

def generate_response(prompt, max_new_tokens=200):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.1,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id,
        )
    response = tokenizer.decode(out[0], skip_special_tokens=True)
    if "[/INST]" in response:
        response = response.split("[/INST]")[-1].strip()
    return response

# --- TEST BEFORE FINE-TUNING ---
test_samples = [dataset["test"][i] for i in [0, 10, 50]]

print("\n" + "=" * 60)
print("BEFORE FINE-TUNING")
print("=" * 60)

before_results = []
for i, sample in enumerate(test_samples):
    prompt = create_prompt(sample)
    response = generate_response(prompt)
    print(f"\n--- Example {i+1} ---")
    print(f"Question: {sample['sql_prompt']}")
    print(f"Expected: {sample['sql']}")
    print(f"Model:    {response[:300]}")
    before_results.append({
        "question": sample["sql_prompt"],
        "expected": sample["sql"],
        "output": response,
    })

# --- CLEAR MEMORY BEFORE TRAINING ---
gc.collect()
torch.cuda.empty_cache()

# --- FORMAT TRAINING DATA ---
def format_training_sample(sample):
    return f"""[INST] You are a helpful SQL assistant. Given the following database schema and a natural language question, generate the correct SQL query and explain what it does.

### Database Schema:
{sample["sql_context"]}

### Question:
{sample["sql_prompt"]}

### Response:
[/INST]
**SQL Query:**
{sample["sql"]}

**Explanation:**
{sample["sql_explanation"]}"""

train_data = dataset["train"].shuffle(seed=42).select(range(1000))
train_data = train_data.map(lambda s: {"formatted_text": format_training_sample(s)})
formatted_dataset = train_data.map(
    lambda x: {"text": x["formatted_text"]},
    remove_columns=train_data.column_names,
)
print(f"\nTraining samples: {len(formatted_dataset)}")

# --- CONFIGURE LORA + TRAINING ---
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
)

training_args = TrainingArguments(
    output_dir="./mistral-sql-lora",
    num_train_epochs=1,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    bf16=True,
    logging_steps=10,
    save_strategy="no",
    optim="paged_adamw_8bit",
    warmup_steps=10,
    max_grad_norm=0.3,
    report_to="none",
)

trainer = SFTTrainer(
    model=model,
    train_dataset=formatted_dataset,
    peft_config=lora_config,
    processing_class=tokenizer,
    args=training_args,
)

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total = sum(p.numel() for p in model.parameters())
print(f"Trainable: {trainable:,} / {total:,} ({trainable/total*100:.2f}%)")
print("Starting training...\n")

# --- TRAIN ---
trainer.train()
print("\n✅ Training complete!")

# --- TEST AFTER FINE-TUNING ---
model.config.use_cache = True

print("\n" + "=" * 60)
print("AFTER FINE-TUNING")
print("=" * 60)

after_results = []
for i, sample in enumerate(test_samples):
    prompt = create_prompt(sample)
    response = generate_response(prompt)
    print(f"\n--- Example {i+1} ---")
    print(f"Question: {sample['sql_prompt']}")
    print(f"Expected: {sample['sql']}")
    print(f"Model:    {response[:300]}")
    after_results.append({
        "question": sample["sql_prompt"],
        "expected": sample["sql"],
        "output": response,
    })

# --- BEFORE vs AFTER COMPARISON ---
print("\n" + "=" * 60)
print("BEFORE vs AFTER COMPARISON")
print("=" * 60)
for i in range(len(test_samples)):
    print(f"\n{'='*60}")
    print(f"Example {i+1}: {before_results[i]['question']}")
    print(f"{'='*60}")
    print(f"✅ Expected:\n{before_results[i]['expected']}")
    print(f"\n❌ Before fine-tuning:\n{before_results[i]['output'][:300]}")
    print(f"\n🟢 After fine-tuning:\n{after_results[i]['output'][:300]}")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 528.8/528.8 kB 19.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 15.0 MB/s eta 0:00:00
GPU: Tesla T4
GPU memory: 15.6 GB

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

synthetic_text_to_sql_train.snappy.parqu(…):   0%|          | 0.00/32.4M [00:00<?, ?B/s]

synthetic_text_to_sql_test.snappy.parque(…):   0%|          | 0.00/1.90M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/100000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/5851 [00:00<?, ? examples/s]

Train: 100000, Test: 5851

config.json:   0%|          | 0.00/596 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

Model loaded: 4.0 GB

============================================================
BEFORE FINE-TUNING
============================================================

--- Example 1 ---
Question: What is the average explainability score of creative AI applications in 'Europe' and 'North America' in the 'creative_ai' table?
Expected: SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'North America');
Model:    To answer the question, we need to calculate the average explainability score for creative AI applications in both 'Europe' and 'North America' regions. Here's the SQL query to achieve that:

```sql
SELECT region, AVG(explainability_score) as avg_explainability_score
FROM creative_ai
GROUP BY region

--- Example 2 ---
Question: How many decentralized applications have been downloaded from the 'Asia-Pacific' region?
Expected: SELECT SUM(dapp_downloads) FROM dapp_ranking WHERE dapp_region = 'Asia-Pacific';
Model:    Based on the given database schema and question, the SQL query to answer the question would be:

```sql
SELECT COUNT(dapp_downloads)
FROM dapp_ranking
WHERE dapp_region = 'Asia-Pacific';
```

Explanation:
The query uses the `SELECT` statement to retrieve the number of rows (i.e., decentralized appli

--- Example 3 ---
Question: What is the number of patients in India who received group therapy?
Expected: SELECT COUNT(*) FROM patients INNER JOIN treatments ON patients.id = treatments.patient_id WHERE treatments.treatment = 'Group Therapy' AND patients.country = 'India';
Model:    To answer the question, we need to join the `patients` and `treatments` tables using the `patient_id` and filter the results to only include patients from India and the treatment type as 'Group Therapy'. We can then use the `COUNT` function to get the number of matching records.

Here's the SQL quer

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Training samples: 1000

Adding EOS to train dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 2}.

Trainable: 13,631,488 / 3,765,702,656 (0.36%)
Starting training...

✅ Training complete!

============================================================
AFTER FINE-TUNING
============================================================

--- Example 1 ---
Question: What is the average explainability score of creative AI applications in 'Europe' and 'North America' in the 'creative_ai' table?
Expected: SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'North America');
Model:    **SQL Query:**
SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'North America');

**Explanation:**
This query calculates the average explainability score of creative AI applications in 'Europe' and 'North America' in the 'creative_ai' table. It uses the AVG function to c

--- Example 2 ---
Question: How many decentralized applications have been downloaded from the 'Asia-Pacific' region?
Expected: SELECT SUM(dapp_downloads) FROM dapp_ranking WHERE dapp_region = 'Asia-Pacific';
Model:    **SQL Query:**
SELECT COUNT(*) FROM dapp_ranking WHERE dapp_region = 'Asia-Pacific';

**Explanation:**
This query counts the number of decentralized applications downloaded from the 'Asia-Pacific' region by filtering the dapp_region column for the 'Asia-Pacific' value and then counting the number of

--- Example 3 ---
Question: What is the number of patients in India who received group therapy?
Expected: SELECT COUNT(*) FROM patients INNER JOIN treatments ON patients.id = treatments.patient_id WHERE treatments.treatment = 'Group Therapy' AND patients.country = 'India';
Model:    **SQL Query:**
SELECT COUNT(*) FROM patients INNER JOIN treatments ON patients.id = treatments.patient_id WHERE patients.country = 'India' AND treatments.treatment = 'Group Therapy';

**Explanation:**
This query joins the patients and treatments tables on the patient_id column, filters for patients

============================================================
BEFORE vs AFTER COMPARISON
============================================================

============================================================
Example 1: What is the average explainability score of creative AI applications in 'Europe' and 'North America' in the 'creative_ai' table?
============================================================
✅ Expected:
SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'North America');

❌ Before fine-tuning:
To answer the question, we need to calculate the average explainability score for creative AI applications in both 'Europe' and 'North America' regions. Here's the SQL query to achieve that:

```sql
SELECT region, AVG(explainability_score) as avg_explainability_score
FROM creative_ai
GROUP BY region

🟢 After fine-tuning:
**SQL Query:**
SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'North America');

**Explanation:**
This query calculates the average explainability score of creative AI applications in 'Europe' and 'North America' in the 'creative_ai' table. It uses the AVG function to c

============================================================
Example 2: How many decentralized applications have been downloaded from the 'Asia-Pacific' region?
============================================================
✅ Expected:
SELECT SUM(dapp_downloads) FROM dapp_ranking WHERE dapp_region = 'Asia-Pacific';

❌ Before fine-tuning:
Based on the given database schema and question, the SQL query to answer the question would be:

```sql
SELECT COUNT(dapp_downloads)
FROM dapp_ranking
WHERE dapp_region = 'Asia-Pacific';
```

Explanation:
The query uses the `SELECT` statement to retrieve the number of rows (i.e., decentralized appli

🟢 After fine-tuning:
**SQL Query:**
SELECT COUNT(*) FROM dapp_ranking WHERE dapp_region = 'Asia-Pacific';

**Explanation:**
This query counts the number of decentralized applications downloaded from the 'Asia-Pacific' region by filtering the dapp_region column for the 'Asia-Pacific' value and then counting the number of

============================================================
Example 3: What is the number of patients in India who received group therapy?
============================================================
✅ Expected:
SELECT COUNT(*) FROM patients INNER JOIN treatments ON patients.id = treatments.patient_id WHERE treatments.treatment = 'Group Therapy' AND patients.country = 'India';

❌ Before fine-tuning:
To answer the question, we need to join the `patients` and `treatments` tables using the `patient_id` and filter the results to only include patients from India and the treatment type as 'Group Therapy'. We can then use the `COUNT` function to get the number of matching records.

Here's the SQL quer

🟢 After fine-tuning:
**SQL Query:**
SELECT COUNT(*) FROM patients INNER JOIN treatments ON patients.id = treatments.patient_id WHERE patients.country = 'India' AND treatments.treatment = 'Group Therapy';

**Explanation:**
This query joins the patients and treatments tables on the patient_id column, filters for patients

In [2]:
# --- EVALUATION ON 20 TEST SAMPLES ---
import re

def extract_sql_from_response(response):
    """Extract just the SQL query from model output"""
    # After fine-tuning, format is **SQL Query:** ... **Explanation:**
    if "**SQL Query:**" in response:
        sql = response.split("**SQL Query:**")[1]
        if "**Explanation:**" in sql:
            sql = sql.split("**Explanation:**")[0]
        return sql.strip()
    # Before fine-tuning, SQL might be in ```sql blocks
    if "```sql" in response:
        sql = response.split("```sql")[1]
        if "```" in sql:
            sql = sql.split("```")[0]
        return sql.strip()
    return response.strip()

def simple_sql_match(predicted, expected):
    """Normalize and compare SQL queries"""
    def normalize(s):
        s = s.lower().strip().rstrip(";")
        s = re.sub(r'\s+', ' ', s)
        return s
    return normalize(predicted) == normalize(expected)

# Evaluate on 20 test samples
eval_indices = list(range(0, 200, 10))  # 20 samples spread across test set
correct_before = 0
correct_after = 0
results_table = []

print("Evaluating 20 test samples...")
print("=" * 60)

for idx in eval_indices:
    sample = dataset["test"][idx]
    prompt = create_prompt(sample)

    # Generate after fine-tuning
    after_response = generate_response(prompt)
    after_sql = extract_sql_from_response(after_response)

    # Check match
    expected = sample["sql"]
    match = simple_sql_match(after_sql, expected)
    if match:
        correct_after += 1

    results_table.append({
        "question": sample["sql_prompt"][:80],
        "expected_sql": expected[:80],
        "generated_sql": after_sql[:80],
        "match": "✅" if match else "❌",
    })

print(f"\nAfter fine-tuning accuracy (exact match): {correct_after}/{len(eval_indices)} = {correct_after/len(eval_indices)*100:.0f}%")

# Show results as table
results_df = pd.DataFrame(results_table)
print("\n")
print(results_df.to_string(index=False))

# --- GRADIO INTERFACE ---
def query_model(schema, question):
    sample = {"sql_context": schema, "sql_prompt": question}
    prompt = create_prompt(sample)
    response = generate_response(prompt, max_new_tokens=300)
    return response

demo = gr.Interface(
    fn=query_model,
    inputs=[
        gr.Textbox(
            label="Database Schema",
            placeholder="CREATE TABLE employees (id INT, name TEXT, department TEXT, salary INT);",
            lines=4,
        ),
        gr.Textbox(
            label="Your Question",
            placeholder="Show me all employees in the sales department",
            lines=2,
        ),
    ],
    outputs=gr.Textbox(label="Generated SQL + Explanation", lines=8),
    title="🔍 Text-to-SQL — Fine-tuned Mistral-7B",
    description="Enter a database schema and ask a question in plain English. The fine-tuned model will generate the SQL query and explain it.",
    examples=[
        [
            "CREATE TABLE employees (id INT, name TEXT, department TEXT, salary REAL);",
            "What is the average salary of employees in each department?"
        ],
        [
            "CREATE TABLE orders (order_id INT, customer_id INT, product TEXT, amount REAL, order_date DATE);",
            "Find the total amount spent by each customer in 2024"
        ],
        [
            "CREATE TABLE students (id INT, name TEXT, grade INT, city TEXT); CREATE TABLE scores (student_id INT, subject TEXT, score INT);",
            "What is the average score of students from New York?"
        ],
    ],
)

print("\nLaunching Gradio interface...")
demo.launch(share=True)

Evaluating 20 test samples...
============================================================

After fine-tuning accuracy (exact match): 4/20 = 20%


                                                                        question                                                                     expected_sql                                                                    generated_sql match
What is the average explainability score of creative AI applications in 'Europe' SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'No SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'No     ✅
How many decentralized applications have been downloaded from the 'Asia-Pacific' SELECT SUM(dapp_downloads) FROM dapp_ranking WHERE dapp_region = 'Asia-Pacific';            SELECT COUNT(*) FROM dapp_ranking WHERE dapp_region = 'Asia-Pacific';     ❌
            Which rural areas have the highest prevalence of asthma in children? SELECT county, state, AVG(prevalence) AS avg_prevalence FROM asthma WHERE age <  SELECT county, state, age, prevalence FROM asthma WHERE age BETWEEN 0 AND 17 AND     ❌
List renewable energy projects in India with a budget between $50 million and $2 SELECT name FROM renewable_project WHERE country = 'India' AND budget BETWEEN 50 SELECT * FROM renewable_project WHERE country = 'India' AND budget BETWEEN 50000     ❌
         What is the total revenue generated by sales of eco-friendly materials? SELECT SUM(revenue) FROM Sales WHERE material IN ('Organic Cotton', 'Hemp', 'Rec SELECT SUM(revenue) FROM Sales WHERE material IN ('Organic Cotton', 'Hemp', 'Rec     ✅
             What is the number of patients in India who received group therapy? SELECT COUNT(*) FROM patients INNER JOIN treatments ON patients.id = treatments. SELECT COUNT(*) FROM patients INNER JOIN treatments ON patients.id = treatments.     ❌
Which mobile plans have a higher data limit than the average data limit for all  SELECT plan_name FROM mobile_plans WHERE data_limit > (SELECT AVG(data_limit) FR SELECT plan_name, AVG(data_limit) as avg_data_limit FROM mobile_plans GROUP BY p     ❌
What is the total revenue and food safety risk score for each menu item in 'Fine SELECT r.name AS restaurant, mi.name AS menu_item, mi.risk_score, SUM(mi.revenue SELECT m.name, SUM(m.revenue) AS total_revenue, AVG(mi.risk_score) AS avg_risk_s     ❌
What is the count of vessels that have visited a specific port in a given month? SELECT COUNT(PortCalls.id) FROM PortCalls WHERE PortCalls.port = 'PortA' AND Por SELECT COUNT(DISTINCT Vessels.id) FROM Vessels INNER JOIN PortCalls ON Vessels.i     ❌
What is the ratio of successful community education programs to total programs f SELECT Country, COUNT(*) FILTER (WHERE Success) * 1.0 / COUNT(*) as SuccessRate  SELECT Country, ROUND(SUM(Success) / SUM(Programs) * 100, 2) AS Success_Ratio FR     ❌
                                Show the sum of investments by year and industry SELECT investment_year, industry, SUM(investment_amount) as total_investments FR SELECT investment_year, industry, SUM(investment_amount) as total_investment FRO     ❌
List all transactions with a value greater than $10,000, along with the customer SELECT * FROM transactions WHERE transaction_value > 10000 ORDER BY transaction_ SELECT customer_id, transaction_date, transaction_value FROM transactions WHERE      ❌
                                   What is the maximum solar capacity in Mexico?               SELECT MAX(capacity) FROM solar_capacity WHERE country = 'Mexico';               SELECT MAX(capacity) FROM solar_capacity WHERE country = 'Mexico';     ✅
List all suppliers from India with more than 3 delivery incidents in the last 6  SELECT supplier_name, country FROM FoodSuppliers WHERE country = 'India' AND del SELECT supplier_name FROM FoodSuppliers WHERE country = 'India' AND delivery_inc     ❌
Delete pollution records from the ocean_pollution table that are older than 10 y DELETE FROM ocean_pollution WHERE pollution_date < (CURRENT_DATE - INTERVAL '10  DELETE FROM ocean_pollution WHERE pollution_date < DATE_SUB(CURRENT_DATE, INTERV     ❌
What is the total number of customer complaints regarding mobile and broadband s SELECT region, COUNT(*) AS total_complaints FROM complaints WHERE complaint_type SELECT complaint_type, region, COUNT(*) as total_complaints FROM complaints GROU     ❌
What is the average property value in historically underrepresented communities? SELECT AVG(Property_Value) FROM Property_Value_History pvh JOIN Property_Details SELECT AVG(Property_Value_History.Property_Value) FROM Property_Value_History IN     ❌
                  Remove the 'Zero-day exploit' record from the 'exploits' table                              DELETE FROM exploits WHERE name='Zero-day exploit';                            DELETE FROM exploits WHERE name = 'Zero-day exploit';     ❌
         List the top 3 countries with the highest number of satellites launched SELECT Country, COUNT(*) as SatelliteCount, RANK() OVER(ORDER BY COUNT(*) DESC)  SELECT Country, COUNT(*) as SatellitesLaunched FROM Satellites GROUP BY Country      ❌
What is the total number of transactions performed by all decentralized applicat                                               SELECT COUNT(*) FROM transactions;                                               SELECT COUNT(*) FROM transactions;     ✅

NameError: name 'gr' is not defined

In [3]:
import gradio as gr

demo = gr.Interface(
    fn=query_model,
    inputs=[
        gr.Textbox(
            label="Database Schema",
            placeholder="CREATE TABLE employees (id INT, name TEXT, department TEXT, salary INT);",
            lines=4,
        ),
        gr.Textbox(
            label="Your Question",
            placeholder="Show me all employees in the sales department",
            lines=2,
        ),
    ],
    outputs=gr.Textbox(label="Generated SQL + Explanation", lines=8),
    title="🔍 Text-to-SQL — Fine-tuned Mistral-7B",
    description="Enter a database schema and ask a question in plain English. The fine-tuned model will generate the SQL query and explain it.",
    examples=[
        [
            "CREATE TABLE employees (id INT, name TEXT, department TEXT, salary REAL);",
            "What is the average salary of employees in each department?"
        ],
        [
            "CREATE TABLE orders (order_id INT, customer_id INT, product TEXT, amount REAL, order_date DATE);",
            "Find the total amount spent by each customer in 2024"
        ],
        [
            "CREATE TABLE students (id INT, name TEXT, grade INT, city TEXT); CREATE TABLE scores (student_id INT, subject TEXT, score INT);",
            "What is the average score of students from New York?"
        ],
    ],
)

print("Launching Gradio interface...")
demo.launch(share=True)

Launching Gradio interface...
Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://5c023a11fb587761c2.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)